### ISSUE TITLE
can you please add support for in-memory storage

### ISSUE THREAD

**Issue by srineelesh** [sourcefuse/loopback4-ratelimiter#4] opened 2020-09-25 09:54 UTC
can you please add support for in-memory storage. Alternatively, would you accept a PR for that ?

**Comment by akshatdubeysf** [comment] 2021-09-06 09:09
@srineelesh we added support for in memory store in last release, can you check if that works for you.

**Comment by akshatdubeysf** [comment] 2021-12-06 07:12
@srineelesh we have merged the PR that resolves the issue, and we are closing the issue, if you find the issue is not resolved for you, you can reopen this issue.

**Closed** 2021-12-06 07:13 UTC
