### ISSUE TITLE
Redis rate limiter

### ISSUE THREAD

**Issue by jhimy-michel** [sourcefuse/loopback4-ratelimiter#9] opened 2021-02-24 20:50 UTC
Im implementing a rate limiter in my loopback4 project and I have some issues when trying to customize the values for the rate-limit config. Im using the redis-loopback-connector.
For example:
```
this.bind(RateLimitSecurityBindings.CONFIG).to({
     name: 'redis',
      max: 20, // limit each IP to 20 requests per windowMs
      windowMs: 1 * 1000, // one second
      keyGenerator: rateLimitKeyGen,
    });
```
Im trying to set the max parameter to 20 and windowMs to 1000 ms, but it looks like the windowMs parameter is being ignored because when Im testing it is using the default value 6000 ms.
Does anyone know how I can fix this?

**Comment by samarpan-b** [comment] 2021-05-13 09:13
Seems like a bug. @akshatdubeysf can you put a fix to this asap?

**Comment by akshatdubeysf** [comment] 2021-06-23 11:16
@jhimy-michel can you confirm if this issue is resolved?

**Comment by akshatdubeysf** [comment] 2021-12-06 07:14
@jhimy-michel we have merged the PR that resolves the issue, and we are closing the issue, if you find the issue is not resolved for you, you can reopen this issue.

**Closed by akshatdubeysf** 2021-12-06 07:14 UTC
